Product.create!([
  {name: "Apple Macbook Pro 2", price: "2349.0", image: "http://store.storeimages.cdn-apple.com/4939/as-images.apple.com/is/image/AppleInc/aos/published/images/m/ac/macbook/pro/macbook-pro-15-select-hero-201505?wid=267&hei=156&fmt=png-alpha&qlt=95&.v=1433482384585", description: "15 inch Macbook Pro with Retina display, 2.5 GHz processor, 512 GB storage.", inventory: 2},
  {name: "Apple iPad Mini 2", price: "319.0", image: "http://store.storeimages.cdn-apple.com/4939/as-images.apple.com/is/image/AppleInc/aos/published/images/i/pa/ipad/mini/ipad-mini-retina-step1-black-2013_GEO_US?wid=150&hei=195&fmt=png-alpha&qlt=95&.v=1442285784019", description: "Apple iPad Mini 2, space gray, 32 GB, Wi-Fi", inventory: 1},
  {name: "Apple TV", price: "149.0", image: "http://store.storeimages.cdn-apple.com/4939/as-images.apple.com/is/image/AppleInc/aos/published/images/a/pp/apple/tv/apple-tv-hero-select-201510?wid=538&hei=535&fmt=jpeg&qlt=95&op_sharpen=0&resMode=", description: "Apple TV, 32 GB", inventory: nil},
  {name: "The West Wing: The Complete Series Collection", price: "85.0", image: "http://ecx.images-amazon.com/images/I/41Ecx-kpi9L.jpg", description: "A box set of all seven fantastic seasons written (through season 3) by the great Aaron Sorkin. You are investing in the best show of all time. Actually priceless, but if we must, yours for only $100", inventory: 1},
  {name: "Studio 60 on the Sunset Strip - The Complete Series", price: "30.0", image: "http://ecx.images-amazon.com/images/I/91IErD5%2BcQL._SL1500_.jpg", description: "Matthew Perry and Bradley Whitford head the cast as comedy writer Matt and executive producer Danny, former Studio 60 hands whom Jordan brings back to save the show. A++ work by the greatest of writers, Aaron Sorkin.", inventory: 3},
  {name: "The Newsroom - Complete Series (Blu-ray)", price: "60.0", image: "http://ecx.images-amazon.com/images/I/812lKUGg6qL._SL1500_.jpg", description: "Gone too soon, relive all 25 episodes of The Newsroom. Seasons 1-3 of the HBO show in one complete set", inventory: 2},
  {name: "Sports Night - The Complete Series Boxed Set", price: "19.99", image: "http://ecx.images-amazon.com/images/I/51YMXPJVPGL.jpg", description: "Before the greatness of The West Wing, came Aaron Sorkin's Sports Night. A show following an energetic television staff scrambling to put on a nightly cable sports show. Enjoy the full series for only $20.", inventory: 1},
  {name: "The West Wing Script Book", price: "10.0", image: "http://ecx.images-amazon.com/images/I/51xklzu%2Br4L.jpg", description: "First time publication of 6 full scripts from the hit NBC show The West Wing.", inventory: 1},
  {name: "A Few Good Men", price: "12.0", image: "http://ecx.images-amazon.com/images/I/51OMcSx7CcL.jpg", description: "Tom Cruise, Jack Nicholson, and Demi Moore star in a drama about the dangerous difference between following orders and following one's conscience.", inventory: 1},
  {name: "Anthony Rizzo Cubs Jersey", price: "220.0", image: "http://www.yomister.com/image/large/iPZ8kLwDT=7pjvVEkugBjalt6qcrj=8h/UploadFiles/2012102664411688.14.jpg", description: "Authentic Chicago Cubs Anthony Rizzo Home Jersey.", inventory: 1},
  {name: "Coke Classic", price: "3.0", image: "http://cdn.shopify.com/s/files/1/0269/2121/products/Mexi_Coke_large.jpg?v=1450029154", description: "Delicious drink, in a classic glass bottle.", inventory: 6},
  {name: "Vitamin Water Zero", price: "1.0", image: "http://smartcanucks.ca/wp-content/uploads/2013/01/vitamin-water-zer0.png", description: "Vitamin water zero, squeezed lemonade flavor", inventory: 10}
])
